### ISSUE TITLE
DELETE does not support query strings

### ISSUE THREAD

**Issue by zopyx** [plone/plone.rest#33] opened 2015-12-15 12:31 UTC
Not a bug in plone.rest (but likely within the Zpublisher) but worth being noticed:

DELETE requests with a query string do not work in Zope. The query string seems to be ignored or removed somewhere in the ZPublisher but it does not show up in the requests.

Deleting a resource using

DELETE http://.../path/to/resource

works.

This won't work:

DELETE http://.../path/to/resource/my-endpoint?name=xxx

Perhaps this should be added to the documentation as limitation.

**Comment by buchi** [comment] 2016-05-19 18:20
Closing this as I can't reproduce it. Query strings in DELETE requests work for me with the current version of plone.rest. If you still have this problem, please provide an example implementation of your service that causes the problem.

**Closed by buchi** 2016-05-19 18:20 UTC
